mysite/lab2/urls.py
from django.urls import path
from . import views

app_name = 'lab2'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('send', views.send_message, name="send"),
    path('inbox', views.view_messages, name="inbox"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab2.urls')),
]

mysite/lab2/models.py
from django.db import models

# Create your models here.

mysite/lab2/forms.py
from django import forms


class GmailMessageForm(forms.Form):
    sender_email = forms.EmailField(label='Your Email')
    sender_password = forms.CharField(label='Your Password', widget=forms.PasswordInput)
    recipient_email = forms.EmailField(label='Recipient Email')
    subject = forms.CharField(label='Subject', max_length=100)
    message = forms.CharField(label='Message', widget=forms.Textarea)


class GmailInboxForm(forms.Form):
    email = forms.EmailField(label='Your Email')
    password = forms.CharField(label='Your Password', widget=forms.PasswordInput)

mysite/lab2/views.py
from django.shortcuts import render
from .forms import GmailMessageForm, GmailInboxForm
from django.core.mail import send_mail
from .get_messages import read_emails
import time


# Create your views here.
def home_view(request):
    return render(request, 'lab2/home.html')


def send_message(request):
    sent = False
    if request.method == 'POST':
        form = GmailMessageForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            sender_email = cd.get('sender_email')
            recipient_email = cd.get('recipient_email')
            subject = cd.get('subject')
            message = cd.get('message')
            password = cd.get('sender_password')
            send_mail(subject=subject,
                      message=message,
                      from_email=sender_email,
                      recipient_list=[recipient_email],
                      auth_user=sender_email,
                      auth_password=password)
            sent = True
    else:
        form = GmailMessageForm()
    return render(request, 'lab2/send.html', {'form': form, 'sent': sent})


def view_messages(request):
    get = False
    messages = {}
    if request.method == 'POST':
        form = GmailInboxForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            email = cd.get('email')
            password = cd.get('password')
            messages = read_emails(email, password)
            messages = dict(reversed(list(messages.items())))
            # time.sleep(1)
            get = True
    else:
        form = GmailInboxForm()

    return render(request, 'lab2/get.html', {'form': form, 'messages': messages, 'get': get})

mysite/lab2/templates/lab2/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'lab2/css/styles.css' %}">
    <link rel="icon" href="{% static 'lab2/favicon/favicon.png' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <a href="{% url 'lab2:home' %}">Home</a>
    <a href="{% url 'lab2:send' %}">Send message</a>
    <a href="{% url 'lab2:inbox' %}">Check inbox</a>
</header>
<div class="separator"></div>
{% block body %}
{% endblock %}
</body>
</html>

mysite/lab2/templates/lab2/get.html
{% extends "lab2/base.html" %}
{% block title %}Inbox{% endblock %}
{% block body %}
<div class="inbox">
    {% if get %}
        <h1>Your inbox: </h1>
        {% for email_id, email_info in messages.items %}
            <div class="message">
                <p>From: {{ email_info.From }}</p>
                <p>Subject: {{ email_info.Subject }}</p>
                <p>Date: {{ email_info.Date }}</p>
                <p>Body: {{ email_info.Body }}</p>
            </div>
        {% endfor %}

    {% else %}
        <h1>Fill form to check inbox</h1>
        <form method="post">
           <div class="form-row">
               <label for="id_email">Your Email</label>
               {{ form.email }}
           </div>
           <div class="form-row">
               <label for="id_password">Your Password</label>
               {{ form.password }}
           </div>
           {% csrf_token %}
           <input type="submit" value="Check inbox">
       </form>
    {% endif %}


</div>

{% endblock %}

mysite/lab2/templates/lab2/home.html
{% extends "lab2/base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="home">
    This is home page.
</div>

{% endblock %}

mysite/lab2/templates/lab2/send.html
{% extends "lab2/base.html" %}
{% block title %}Send{% endblock %}
{% block body %}
<div class="send">
   {% if sent %}
       <h1>E-mail successfully sent</h1>
       <p>
           Your message was successfully sent
           to {{ form.cleaned_data.recipient_email }}.
       </p>
   {% else %}
       <h1>Fill form to send e-mail</h1>
       <form method="post">
           <div class="form-row">
               <label for="id_sender_email">Your Email</label>
               {{ form.sender_email }}
           </div>
           <div class="form-row">
               <label for="id_sender_password">Your Password</label>
               {{ form.sender_password }}
           </div>
           <div class="form-row">
               <label for="id_recipient_email">Recipient Email</label>
               {{ form.recipient_email }}
           </div>
           <div class="form-row">
               <label for="id_subject">Subject</label>
               {{ form.subject }}
           </div>
           <div class="form-row">
               <label for="id_message">Message</label>
               {{ form.message }}
           </div>
           {% csrf_token %}
           <input type="submit" value="Send e-mail">
       </form>
   {% endif %}
</div>

{% endblock %}